# Generated by Django 5.2 on 2025-11-18 19:01

from django.db import migrations, models


def normalize_image_paths(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    for product in Product.objects.exclude(image_url=""):
        name = product.image_url.name
        if name.startswith("/images/uploads/"):
            product.image_url = name.split("/images/uploads/", 1)[1]
            product.save(update_fields=["image_url"])
        elif name.startswith("/images/"):
            product.image_url = ""
            product.save(update_fields=["image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(blank=True, upload_to="", verbose_name="image"),
        ),
        migrations.RunPython(normalize_image_paths, migrations.RunPython.noop),
    ]
